version: '3.8'

services:
  img-hub:
    image: wangbar01334/img-hub:latest
    container_name: img-hub-app
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      # 只挂载动态内容，保留容器内的静态icon文件
      - ./public/images:/usr/share/nginx/html/public/images:ro
      - ./public/albums.json:/usr/share/nginx/html/public/albums.json:ro
    environment:
      - NODE_ENV=production
    networks:
      - img-hub-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.img-hub.rule=Host(`localhost`)"
      - "traefik.http.services.img-hub.loadbalancer.server.port=80"

networks:
  img-hub-network:
    driver: bridge

volumes:
  img-storage:
    driver: local
