version: '3.8'

services:
  img-hub:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: img-hub-server
    restart: unless-stopped
    volumes:
      # 持久化数据目录
      - ./data:/app/data:rw
      - ./public/images:/app/public/images:rw
      - ./public/albums.json:/app/public/albums.json:rw
      # 应用日志持久化
      - ./logs:/app/logs:rw
    
    environment:
      - NODE_ENV=production
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - JWT_SECRET=${JWT_SECRET:-img-hub-admin-secret-key-2024}
      - PORT=3000
      - FORCE_HTTPS=${FORCE_HTTPS:-false}
    networks:
      - img-hub-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  nginx:
    image: nginx:alpine
    container_name: img-hub-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-https.conf:/etc/nginx/conf.d/default.conf:ro
      # SSL证书挂载 (如果启用HTTPS)
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - img-hub
    networks:
      - img-hub-network

networks:
  img-hub-network:
    driver: bridge
