version: '3.8'

services:
  img-hub:
    build: .  # 本地构建而不是使用Docker Hub镜像
    container_name: img-hub-local
    restart: unless-stopped
    ports:
      # 直接暴露3000端口，不使用nginx代理
      - "3000:3000"
    volumes:
      # 持久化数据目录
      - ./data:/app/data:rw
      - ./public/images:/app/public/images:rw
      # 应用日志持久化（重要：用于测试文件日志）
      - ./logs:/app/logs:rw
    
    environment:
      - NODE_ENV=production
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - JWT_SECRET=${JWT_SECRET:-img-hub-admin-secret-key-2024}
      - PORT=3000
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s