version: '3.8'

services:
  img-hub:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: img-hub-server
    restart: unless-stopped
    ports:
      - "80:3000"
    volumes:
      # 持久化数据目录
      - ./data:/app/data:rw
      - ./public/images:/app/public/images:rw
      # 应用日志持久化
      - ./logs:/app/logs:rw
    
    environment:
      - NODE_ENV=production
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - JWT_SECRET=${JWT_SECRET:-img-hub-admin-secret-key-2024}
      - PORT=3000
    networks:
      - img-hub-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.img-hub.rule=Host(`localhost`)"
      - "traefik.http.services.img-hub.loadbalancer.server.port=3000"

networks:
  img-hub-network:
    driver: bridge
