version: '3.8'

services:
  img-hub:
    image: wangbar01334/img-hub:latest
    container_name: img-hub-app
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      # 持久化数据目录
      - ./data/albums.json:/usr/share/nginx/html/albums.json:rw
      - ./data/images:/usr/share/nginx/html/images:rw
      # Nginx 日志持久化
      - ./logs:/var/log/nginx:rw
    
    environment:
      - NODE_ENV=production
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - JWT_SECRET=${JWT_SECRET:-img-hub-admin-secret-key-2024}
    networks:
      - img-hub-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.img-hub.rule=Host(`localhost`)"
      - "traefik.http.services.img-hub.loadbalancer.server.port=80"

networks:
  img-hub-network:
    driver: bridge
